spring.application.name=usersrv

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=random

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

grpc.server.port=9091
grpc.client.expense-service.address=static://localhost:9092
grpc.client.expense-service.negotiationType=plaintext